version: '3'

services:
  coqui-tts:
    image: ghcr.io/coqui-ai/tts-cpu:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coqui.rule=Host(`coqui.escoladoprofissional.com.br`)"
      - "traefik.http.services.coqui.loadbalancer.server.port=80"  # Porta interna do container
    networks:
      - network_public
    environment:
      - REDIS_HOST=redis  # Se estiver usando o Redis
      - POSTGRES_HOST=postgres  # Se estiver usando o PostgreSQL

networks:
  network_public:
    external: true
