version: '3'

services:
  coqui-tts:
    image: ghcr.io/coqui-ai/tts-cpu:latest  # Ou a tag específica que você deseja usar
    ports:
      - "80:80"  # Mapeie a porta que você deseja expor
    environment:
      - REDIS_HOST=redis  # Se estiver usando o Redis
      - POSTGRES_HOST=postgres  # Se estiver usando o PostgreSQL
    networks:
      - network_public

networks:
  network_public:
    external: true
